# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=3)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
